2025-03-29 21:30:41,656 INFO    MainThread:32266 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-29 21:30:41,656 INFO    MainThread:32266 [wandb_setup.py:_flush():67] Configure stats pid to 32266
2025-03-29 21:30:41,656 INFO    MainThread:32266 [wandb_setup.py:_flush():67] Loading settings from /home/mirko/.config/wandb/settings
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_setup.py:_flush():67] Loading settings from /home/mirko/PycharmProjects/DLA-LAB/LAB_1/wandb/settings
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/mirko/PycharmProjects/DLA-LAB/LAB_1/wandb/run-20250329_213041-fh2k1zus/logs/debug.log
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/mirko/PycharmProjects/DLA-LAB/LAB_1/wandb/run-20250329_213041-fh2k1zus/logs/debug-internal.log
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_init.py:init():761] calling init triggers
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 4, '_wandb': {}}
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_init.py:init():784] starting backend
2025-03-29 21:30:41,657 INFO    MainThread:32266 [wandb_init.py:init():788] sending inform_init request
2025-03-29 21:30:41,659 INFO    MainThread:32266 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-29 21:30:41,659 INFO    MainThread:32266 [wandb_init.py:init():798] backend started and connected
2025-03-29 21:30:41,660 INFO    MainThread:32266 [wandb_init.py:init():891] updated telemetry
2025-03-29 21:30:41,661 INFO    MainThread:32266 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-29 21:30:41,972 ERROR   MainThread:32266 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/mirko/miniconda3/envs/DLA-LAB/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mirko/miniconda3/envs/DLA-LAB/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403: {"data":{"upsertBucket":null},"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}]}
2025-03-29 21:30:42,973 INFO    MsgRouterThr:32266 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
